#pragma once

#include "plugin-settings.hpp"
#include "worker-launcher.hpp"

#include <string>

class QLabel;
class QString;
class QPushButton;
class QComboBox;
class QCheckBox;
class QFrame;
class QGroupBox;
class QLineEdit;
class QSpinBox;
class QTabWidget;
class QTextEdit;
class QTimer;
class QWidget;

namespace odr::plugin {

class PluginUiController {
public:
	explicit PluginUiController(WorkerProcessManager &worker_manager);

	void register_ui();
	void unregister_ui();
	void refresh();

private:
	static void open_settings_from_menu(void *private_data);
	void apply_dock_theme(const std::string &theme);
	void apply_ui_language();
	void show_settings_dialog();
	void save_settings_and_restart(const PluginSettings &settings);
	void request_manual_start();
	void request_manual_stop();
	void request_upload_retry();
	void request_upload_discard();
	void request_upload_mark_uploaded();
	void request_upload_to_youtube();
	void request_save_upload_privacy();
	void request_open_uploaded_youtube();
	void request_select_upload_client_secret();
	void request_open_upload_secrets_folder();
	void request_upload_oauth_authorization();
	void request_upload_oauth_refresh();
	void request_upload_oauth_help();
	bool ensure_upload_secrets_dir(QString &secrets_dir);
	UploadTargetPayload selected_upload_target(const WorkerStatusSnapshot &snapshot) const;
	bool has_selected_upload_target(const WorkerStatusSnapshot &snapshot) const;
	void refresh_upload_queue_selector(const WorkerStatusSnapshot &snapshot);
	void request_edit_metadata();
	void request_preview_upload_metadata();
	void load_latest_metadata_into_dock();
	void load_match_metadata_into_dock(int match_id);
	void load_target_video_preview(int frame_index);
	void load_upload_video_preview(int frame_index);
	void save_metadata_from_dock();
	void render_upload_preview_from_dock();
	void save_inline_settings();
	void toggle_diagnostics_details();
	void request_show_help();
	void request_automatic_setup();
	bool capture_current_screenshot_base64(std::string &frame_base64, std::string &screenshot_path,
					       std::string &error, bool delete_after_read = false);
	void handle_automatic_recording(const WorkerStatusSnapshot &snapshot);
	void handle_automatic_detection_feed(const WorkerStatusSnapshot &snapshot);
	void log_recording_command_result(const char *action, const RecordingCommandResult &result);
	void log_queue_command_result(const char *action, const QueueCommandResult &result);

	WorkerProcessManager &worker_manager_;
	QWidget *dock_widget_ = nullptr;
	QTimer *refresh_timer_ = nullptr;
	QLabel *state_value_ = nullptr;
	QLabel *setup_value_ = nullptr;
	QLabel *recording_value_ = nullptr;
	QLabel *output_value_ = nullptr;
	QLabel *queue_value_ = nullptr;
	QLabel *review_item_value_ = nullptr;
	QLabel *youtube_value_ = nullptr;
	QLabel *upload_target_value_ = nullptr;
	QLabel *upload_text_value_ = nullptr;
	QLabel *upload_blocking_value_ = nullptr;
	QLabel *upload_result_value_ = nullptr;
	QLabel *endpoint_value_ = nullptr;
	QLabel *user_data_value_ = nullptr;
	QLabel *worker_path_value_ = nullptr;
	QLabel *logs_value_ = nullptr;
	QLabel *ownership_value_ = nullptr;
	QLabel *detail_value_ = nullptr;
	QLabel *action_value_ = nullptr;
	QLabel *setup_title_ = nullptr;
	QLabel *setup_label_ = nullptr;
	QLabel *action_label_ = nullptr;
	QLabel *recording_title_ = nullptr;
	QLabel *recording_label_ = nullptr;
	QLabel *output_label_ = nullptr;
	QLabel *upload_title_ = nullptr;
	QLabel *queue_label_ = nullptr;
	QLabel *review_item_label_ = nullptr;
	QLabel *youtube_label_ = nullptr;
	QLabel *upload_target_label_ = nullptr;
	QLabel *upload_text_label_ = nullptr;
	QLabel *upload_blocking_label_ = nullptr;
	QLabel *upload_result_label_ = nullptr;
	QLabel *metadata_title_ = nullptr;
	QLabel *metadata_note_ = nullptr;
	QLabel *metadata_match_label_ = nullptr;
	QLabel *metadata_video_label_ = nullptr;
	QLabel *metadata_video_preview_image_ = nullptr;
	QLabel *upload_video_preview_image_ = nullptr;
	QLabel *metadata_status_label_ = nullptr;
	QLabel *upload_preview_title_label_ = nullptr;
	QLabel *upload_preview_warning_label_ = nullptr;
	QLabel *settings_note_ = nullptr;
	QLabel *help_note_ = nullptr;
	QLabel *automatic_note_ = nullptr;
	QLabel *endpoint_label_ = nullptr;
	QLabel *user_data_label_ = nullptr;
	QLabel *worker_path_label_ = nullptr;
	QLabel *logs_label_ = nullptr;
	QLabel *ownership_label_ = nullptr;
	QLabel *detail_label_ = nullptr;
	QFrame *header_card_ = nullptr;
	QFrame *setup_card_ = nullptr;
	QFrame *recording_card_ = nullptr;
	QFrame *upload_card_ = nullptr;
	QFrame *metadata_card_ = nullptr;
	QFrame *upload_template_card_ = nullptr;
	QGroupBox *diagnostics_group_ = nullptr;
	QTabWidget *dock_tabs_ = nullptr;
	QComboBox *metadata_deck_input_ = nullptr;
	QComboBox *metadata_opponent_input_ = nullptr;
	QLineEdit *metadata_result_input_ = nullptr;
	QLineEdit *metadata_rank_input_ = nullptr;
	QLineEdit *metadata_dp_input_ = nullptr;
	QTextEdit *metadata_memo_input_ = nullptr;
	QLineEdit *upload_title_template_input_ = nullptr;
	QTextEdit *upload_description_template_input_ = nullptr;
	QLineEdit *upload_tags_template_input_ = nullptr;
	QTextEdit *upload_preview_description_ = nullptr;
	QLineEdit *settings_host_input_ = nullptr;
	QLineEdit *settings_port_input_ = nullptr;
	QLineEdit *settings_user_data_input_ = nullptr;
	QComboBox *settings_theme_input_ = nullptr;
	QComboBox *settings_language_input_ = nullptr;
	QComboBox *upload_privacy_input_ = nullptr;
	QComboBox *upload_queue_input_ = nullptr;
	QCheckBox *automatic_detection_enabled_input_ = nullptr;
	QSpinBox *automatic_detection_interval_input_ = nullptr;
	QPushButton *help_button_ = nullptr;
	QPushButton *automatic_setup_button_ = nullptr;
	QPushButton *start_button_ = nullptr;
	QPushButton *stop_button_ = nullptr;
	QPushButton *retry_upload_button_ = nullptr;
	QPushButton *discard_upload_button_ = nullptr;
	QPushButton *mark_uploaded_button_ = nullptr;
	QPushButton *upload_to_youtube_button_ = nullptr;
	QPushButton *save_upload_privacy_button_ = nullptr;
	QPushButton *open_youtube_button_ = nullptr;
	QPushButton *select_oauth_client_secret_button_ = nullptr;
	QPushButton *open_oauth_secrets_folder_button_ = nullptr;
	QPushButton *oauth_authorize_button_ = nullptr;
	QPushButton *oauth_refresh_button_ = nullptr;
	QPushButton *oauth_help_button_ = nullptr;
	QPushButton *edit_upload_metadata_button_ = nullptr;
	QPushButton *edit_metadata_button_ = nullptr;
	QPushButton *go_upload_button_ = nullptr;
	QPushButton *video_preview_frame_1_button_ = nullptr;
	QPushButton *video_preview_frame_2_button_ = nullptr;
	QPushButton *video_preview_frame_3_button_ = nullptr;
	QPushButton *upload_preview_frame_1_button_ = nullptr;
	QPushButton *upload_preview_frame_2_button_ = nullptr;
	QPushButton *upload_preview_frame_3_button_ = nullptr;
	QPushButton *reload_metadata_button_ = nullptr;
	QPushButton *save_metadata_button_ = nullptr;
	QPushButton *render_upload_preview_button_ = nullptr;
	QPushButton *save_inline_settings_button_ = nullptr;
	QPushButton *diagnostics_details_button_ = nullptr;
	std::string dock_theme_ = "classic";
	std::string ui_language_ = "en";
	OverlayStatePayload last_applied_overlay_state_;
	int current_match_id_ = 0;
	int selected_upload_queue_item_id_ = 0;
	int metadata_preview_frame_index_ = 1;
	int upload_preview_frame_index_ = 1;
	bool upload_request_in_progress_ = false;
	std::string last_uploaded_url_;
	bool metadata_loaded_after_worker_ready_ = false;
	bool diagnostics_details_visible_ = false;
	std::string automatic_recording_request_key_;
	long long last_detection_frame_sent_ms_ = 0;
	bool overlay_state_applied_ = false;
	bool tools_menu_registered_ = false;
};

} // namespace odr::plugin
